#!/bin/sh


# ====================================
# Stop commit if no changes are staged
# ====================================

if git diff --cached --quiet; then
    echo "No changes staged for commit. Please stage files first."
    exit 1
fi
